

List<String> getLyrics2() {

  return ['Hope stopped the heart',
  'Lost beaten lie',
  'Cold walk the earth',
  'Love faded white',
  'Gave up the war',
  'I\'ve realized',
  'All will become',
  'All will arise',
  'Stay with me',
  'I hear them call the tide',
  'Take me in',
  'I see the last divide',
  'Hopelessy',
  'I leave this all behind',
  'And I am paralyzed',
  'When the broken fall alive',
  'Let the light take me too',
  'When the waters turn to fire',
  'Heaven, please let me through',
  'Far away, far away',
  'Sorrow has left me here',
  'Far away, far away',
  'Let the light take me in',
  'Fight back the flood',
  'One breath of life',
  'God, take the earth',
  'Forever blind',
  'And now the sun will fade',
  'And all we are is all we made',
  'Stay with me',
  'I hear them call the tide',
  'Take me in',
  'I see the last divide',
  'Hopelessy',
  'I leave this all behind',
  'And I am paralyzed',
  'When the broken fall alive',
  'Let the light take me too',
  'When the waters…'];

}

List<String> getLyrics() {

  return ['Le gusta la velocidad',
  'Lo quiere rápido, rápido',
  'Rápido, rápido',
  'Rápido, rápido',
  'Acelera, baby, prende los motore',
  'La noche apretamo',
  'y no hay quien te controle',
  'De la manera en que lo mueve', 
  'a mí me fascina',
  'Vamos a tomarno', 
  'un shot de adrenalina',
  'Tengo curiosidad',
  'Quiero viajar dentro de ti', 
  'a mucha velocidad',
  'No voy a parar,', 
  'yo no creo en la autoridad',
  'Lo mismo los do queremo',
  'Ella siempre me dice que sí,', 
  'nunca que no',
  'A 200 milla nos vamo sin freno',
  'Le gusta la velocidad',
  'Lo quiеre rápido, rápido',
  'Rápido, rápido',
  'Rápido, rápido',
  'Tú me acelera,', 
  'me acelera',
  'Manéjame a tu manera',
  'y hazlo rápido',
  'Báilame la noche entera',
  'Condúceme a donde quieras,', 
  'pero rápido',
  'Tú me acelera siempre en exceso',
  'Yo solo me disfruto el proceso',
  'Mezclando adrenalina y el sexo',
  'Los dos sin ropa por el expreso',
  'Si no la atiendo,', 
  'ella se me pone furiosa',
  'La vida e una y nunca ha sido', 
  'color de rosa, nah',
  'Lo nuestro e clandestino',
  'La culpa viene siendo del destino',
  'De nada nunca no arrepentimo',
  'Cuando lo hacemo, siempre repetimo',
  'No la descuido',
  'Tú me acelera,', 
  'me acelera',
  'Manéjame a tu manera', 
  'y hazlo rápido',
  'Báilame la noche entera',
  'Condúceme a donde quieras,', 
  'pero rápido (Rochy)',
  'Rápido me tiene (ah),', 
  'no existe quien la frene',
  'Yo solo la persigo,', 
  'yo no sé si me conviene',
  'Le gusta la velocida,', 
  'al peligro no le teme',
  'Ella está botando fuego,', 
  'yo toy loco que me queme',
  'Me robó su mirada,', 
  'bailando me acelera',
  'Estoy bajando por otro,', 
  'que ya me desespera',
  'Me la voy a robar la noche entera',
  'Me está manejando,', 
  'no me importa que', 
  'lo haga como quiera',
  'Un poco de alcohol', 
  'hasta que salga el sol',
  'Alta temperatura botando el calor',
  'El auto botando vapor',
  'Ella lo acelera, va a fundi el motor',
  'Ya está ready pal toque',
  'Esperando que yo', 
  'la seduzca y la toque',
  'Y la nota le explote',
  'Ya estoy imaginando', 
  'que hay debajo e ese escote',
  'Pura candela pa prenderte en fuego',
  'Y hacer que a la ve', 
  'tú caigas en mi juego',
  'Déjate llevar', 
  'por el humo y el alcohol',
  'Que de tu cuerpo', 
  'yo tengo el control',
  'Tú me acelera, me acelera',
  'Manéjame a tu manera y hazlo rápido',
  'Báilame como tú quiera',
  'Condúceme a tu manera, pero rápido'];

}